server:
  port: 6001
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloudpolo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 10.165.12.109:8848   #\u5F00\u542F\u670D\u52A1\u6CE8\u518C\u53D1\u73B0
      config:
        server-addr: 10.165.12.109:8848   #\u5F00\u542Fnacos\u914D\u7F6E
        file-extension: yml
# mybatis
mybatis-plus:
  mapper-locations: classpath:top/poloo**/mapper/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: top.poloo.**.entity
  global-config:
    # \u5173\u95EDMP3.0\u81EA\u5E26\u7684banner
    banner: false
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u4E0D\u64CD\u4F5C", 2:"\u7528\u6237\u8F93\u5165ID",3:"\u6570\u5B57\u578Bsnowflake", 4:"\u5168\u5C40\u552F\u4E00ID UUID", 5:"\u5B57\u7B26\u4E32\u578Bsnowflake";
      id-type: auto
      #\u5B57\u6BB5\u7B56\u7565
      insert-strategy: not_null
      update-strategy: not_null
      #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
      table-underline: true
      # \u903B\u8F91\u5220\u9664\u914D\u7F6E
      # \u903B\u8F91\u5220\u9664\u5168\u5C40\u503C\uFF081\u8868\u793A\u5DF2\u5220\u9664\uFF0C\u8FD9\u4E5F\u662FMybatis Plus\u7684\u9ED8\u8BA4\u914D\u7F6E\uFF09
      logic-delete-value: 1
      # \u903B\u8F91\u672A\u5220\u9664\u5168\u5C40\u503C\uFF080\u8868\u793A\u672A\u5220\u9664\uFF0C\u8FD9\u4E5F\u662FMybatis Plus\u7684\u9ED8\u8BA4\u914D\u7F6E\uFF09
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
